+incdir+$DESIGN_ROOT/$PROJ_DIR/rtl
$DESIGN_ROOT/$PROJ_DIR/rtl/gdefine.v
$DESIGN_ROOT/$PROJ_DIR/rtl/crypto_hashblocks_sha256_me.v
$DESIGN_ROOT/$PROJ_DIR/rtl/crypto_hashblocks_sha256.v
$DESIGN_ROOT/$PROJ_DIR/rtl/crypto_sign.v
$DESIGN_ROOT/$PROJ_DIR/rtl/f32.v
$DESIGN_ROOT/$PROJ_DIR/rtl/fors_sign.v
$DESIGN_ROOT/$PROJ_DIR/rtl/gen_message_random.v
$DESIGN_ROOT/$PROJ_DIR/rtl/hash_message.v
$DESIGN_ROOT/$PROJ_DIR/rtl/in_rom.v
$DESIGN_ROOT/$PROJ_DIR/rtl/krom.v
$DESIGN_ROOT/$PROJ_DIR/rtl/m32.v
$DESIGN_ROOT/$PROJ_DIR/rtl/main_fsm.v
$DESIGN_ROOT/$PROJ_DIR/rtl/thash.v
$DESIGN_ROOT/$PROJ_DIR/rtl/treehash.v
$DESIGN_ROOT/$PROJ_DIR/rtl/wots_sign.v
